#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Feb 12 21:01:38 EST 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_axis_mag_sq_behav -key {Behavioral:sim_1:Functional:tb_axis_mag_sq} -tclbatch tb_axis_mag_sq.tcl -protoinst "protoinst_files/bd_f519.protoinst" -protoinst "protoinst_files/top_level.protoinst" -log simulate.log"
xsim tb_axis_mag_sq_behav -key {Behavioral:sim_1:Functional:tb_axis_mag_sq} -tclbatch tb_axis_mag_sq.tcl -protoinst "protoinst_files/bd_f519.protoinst" -protoinst "protoinst_files/top_level.protoinst" -log simulate.log

