domain_path: /home/daniel/Documents/FPGA-SensorFusion-EdgeAI/sw/artyz7_platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /home/daniel/Xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
