# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/artyz720_pinout.xdc

# Block Designs: bd/top_level/top_level.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level || ORIG_REF_NAME==top_level} -quiet] -quiet

# IP: bd/top_level/ip/top_level_processing_system7_0_0/top_level_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_processing_system7_0_0 || ORIG_REF_NAME==top_level_processing_system7_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_dma_0_0/top_level_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axi_dma_0_0 || ORIG_REF_NAME==top_level_axi_dma_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_smartconnect_0_0/top_level_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_smartconnect_0_0 || ORIG_REF_NAME==top_level_smartconnect_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axis_data_fifo_0_0/top_level_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axis_data_fifo_0_0 || ORIG_REF_NAME==top_level_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_rst_ps7_0_100M_1/top_level_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_rst_ps7_0_100M_1 || ORIG_REF_NAME==top_level_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_gpio_0_0/top_level_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axi_gpio_0_0 || ORIG_REF_NAME==top_level_axi_gpio_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_xfft_0_1/top_level_xfft_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_xfft_0_1 || ORIG_REF_NAME==top_level_xfft_0_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_magnitude_0_0/top_level_magnitude_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_magnitude_0_0 || ORIG_REF_NAME==top_level_magnitude_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axis_fft_cfg_gen_0_0/top_level_axis_fft_cfg_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axis_fft_cfg_gen_0_0 || ORIG_REF_NAME==top_level_axis_fft_cfg_gen_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_mem_intercon_imp_xbar_0/top_level_axi_mem_intercon_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axi_mem_intercon_imp_xbar_0 || ORIG_REF_NAME==top_level_axi_mem_intercon_imp_xbar_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_mem_intercon_imp_auto_pc_0/top_level_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==top_level_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_mem_intercon_imp_auto_us_0/top_level_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==top_level_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_mem_intercon_imp_auto_pc_1/top_level_axi_mem_intercon_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axi_mem_intercon_imp_auto_pc_1 || ORIG_REF_NAME==top_level_axi_mem_intercon_imp_auto_pc_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_mem_intercon_imp_auto_us_1/top_level_axi_mem_intercon_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axi_mem_intercon_imp_auto_us_1 || ORIG_REF_NAME==top_level_axi_mem_intercon_imp_auto_us_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_mem_intercon_1/top_level_axi_mem_intercon_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axi_mem_intercon_1 || ORIG_REF_NAME==top_level_axi_mem_intercon_1} -quiet] -quiet

# XDC: /home/daniel/Documents/FPGA-SensorFusion-EdgeAI/rtl/processor/processor.gen/sources_1/bd/top_level/top_level_ooc.xdc
